chgmgmt_build/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SLASerialNumber__c</fullName>
        <label>SLA Serial Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

chgmgmt_build/src/objects/Drivers__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>商談</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drivers</relationshipLabel>
        <relationshipName>Drivers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Driver</label>
    <nameField>
        <label>Ve名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

chgmgmt_build/src/classes/CreateOpportunityTriggerTest.cls
@isTest
public class CreateOpportunityTriggerTest {
    @isTest
    public static void CreateOpportunityLogicTest(){
        Account ac = new Account(Name='Test Account',SLA__c='Gold',SLASerialNumber__c='AAA');
        insert ac;
        
        List<Account> acc = [select Id from Account where Name='Test Account'];
        system.debug(acc);
        
        Opportunity op = [select Id,Name from Opportunity where AccountId = :Acc[0].Id];
        If(op != null){
            system.debug(op.Name);
        }
        
        Drivers__c drv = [select Id,Name from Drivers__c where Opportunity__c =:op.Id];
        if(drv != null){
            	system.debug(drv.Name);
        }
        
    }
}