chgmgmt_build/src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation__c</fullName>
        <label>評価</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>名前</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>point__c</fullName>
        <label>ポイント</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>キャンディデイト</label>
    <nameField>
        <label>キャンディデイトID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>キャンディデイト</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

chgmgmt_build/src/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>trace__c</fullName>
        <label>ログトレース</label>
        <type>TextArea</type>
    </fields>
    <label>エラーログ</label>
    <nameField>
        <label>エラーログ名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>エラーログ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

chgmgmt_build/src/classes/EvaulateCandidate.cls
public class EvaulateCandidate {
    
    @future(callout=true)
    public static void EvaluateCandidateREST(Set<ID> ids){
        try{
        Map<ID, Candidate__c> mapCands = findCandidates(ids);
        List<EvaluateCandidateREST.Candidate> listCandidate = new List<EvaluateCandidateREST.Candidate>();
        for (Candidate__c cand : mapCands.values()){
            EvaluateCandidateREST.Candidate can = new EvaluateCandidateREST.Candidate();
            can.Candidate_Id = cand.Name;
            can.Name = cand.Name__c;
            can.Evaluation = cand.Evaluation__c;
            can.Point = (Integer)cand.point__c;
            can.Id = cand.Id;
            listCandidate.add(can);
        }
        
        EvaluateCandidateREST restPort = new EvaluateCandidateREST();
        Set<Integer> IdResult = restPort.EvaluateCandidateREST(listCandidate);
        System.debug(IdResult);
                 
         List<EvaluateCandidateREST.EvCandidate> listResult = restPort.GetCandidateInfo(IdResult);   
        
        for(EvaluateCandidateREST.EvCandidate result : listResult){
            Candidate__c cand = mapCands.get(result.Id);
            cand.point__c = (Decimal)result.Point;

        }
        
        update mapCands.values();
        }catch(Exception ex){
            System.debug('ERROR:' +ex);
            Error_Log__c log = new Error_Log__c();
            log.trace__c = ex.getCause() + '\n' + ex.getMessage();
            insert log;
        }
    }
    
    
    private static Map<ID, Candidate__c> findCandidates(Set<ID> ids){
        	Map<ID, Candidate__c> output;
        output = new Map<ID, Candidate__c>([SELECT ID,Name,Name__c,Evaluation__c,point__c from candidate__c where id in :ids]);
        return output;
    }
    


}