chgmgmt_build/src/objects/feedback360__c.object
<CustomObject>
    <fields>
        <fullName>PDS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>業績目標／パフォーマンス評価</label>
        <referenceTo>PDS__c</referenceTo>
        <relationshipLabel>360度フィードバック</relationshipLabel>
        <relationshipName>PDS_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Q1__c</fullName>
        <label>Q1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Q2__c</fullName>
        <label>Q2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Q3__c</fullName>
        <label>Q3</label>
        <type>TextArea</type>
    </fields>
    <label>360度フィードバック</label>
    <nameField>
        <displayFormat>FB-{0000000}</displayFormat>
        <label>360FB_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

chgmgmt_build/src/objects/PDS__c.object
<CustomObject>
    <label>業績目標／パフォーマンス評価</label>
    <nameField>
        <displayFormat>PDS-{00000000}</displayFormat>
        <label>PDS_No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

chgmgmt_build/src/classes/DEM_FeedbackResultController.cls
public class DEM_FeedbackResultController {
    public PDS__c pds{get;set;}
    public Boolean showError{get;set;}
    public DEM_FeedbackResultController(ApexPages.StandardController controller){
        showError = false;
        pds = (PDS__c)controller.getRecord();
        List<feedback360__c> feedbacks = [Select Q1__c, Q2__c, Q3__c From feedback360__c Where PDS__c = :pds.Id];
        for(feedback360__c fb : feedbacks){
            if(fb.Q1__c == null && fb.Q2__c == null && fb.Q3__c == null){
                showError = true;
            }
        }
    }
}