chgmgmt_build/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Inovices</relationshipLabel>
        <relationshipName>Inovices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inovices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

chgmgmt_build/src/classes/InvoiceExtension.cls
public class InvoiceExtension {
    private final Invoice__c inv;
    
    public string StreetName1{get;set;}
    public string StreetName2{get;set;}
    public string City{get;set;}
    public string State{get;set;}
    public string Zipcode{get;set;}
    
    public InvoiceExtension(Apexpages.StandardController stdController){
        this.inv = (Invoice__c)stdController.getRecord();
        Opportunity opp = [select id,Account.Name,Account.BillingAddress from opportunity where id=:this.inv.Opportunity__c];
        //OpprotunityProduct opp = [select id,productcode from OpportunityProduct where opportunity = :inv.Opportunity];
    }
    
    

}