chgmgmt_build/src/objects/WithdrawalHistory__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WithdrawalHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WithdrawalHistory</label>
    <nameField>
        <label>WithdrawalHistory名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WithdrawalHistory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

chgmgmt_build/src/classes/Utils.cls
public class Utils {
  @future
  public static void createWithdrawalHistory(List<Id> userIds) {
    List<WithdrawalHistory__c> histories = new List<WithdrawalHistory__c>();
    for(Id userId : userIds) {
      WithdrawalHistory__c history = new WithdrawalHistory__c();
      history.User__c = userId;
      histories.add(history);
    }
    if(!histories.isEmpty()) {
      insert histories;
    }
  }
}